import type { Metadata } from "next";
import { Anton } from 'next/font/google'
import "./globals.css";
import SmoothScrollWrapper from "@/components/SmoothScrollWrapper"; // Import du wrapper

const anton = Anton({ weight: '400', subsets: ['latin'] })

export const metadata: Metadata = {
  title: "AKITOMO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr" className="scroll-smooth">
      <body className={`antialiased overflow-x-hidden`}>
        {/* <SmoothScrollWrapper /> */}
       
        {children}
      </body>
    </html>
  );
}
