import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Acceuil | Thomas Zabalo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr" className="scroll-smooth">
      <body className={`antialiased overflow-x-hidden`}>
        {children}
      </body>
    </html>
  );
}
